---
- name: test multiple platforms
  hosts: cisco:arista:juniper:nxos
  gather_facts: False
  tasks:
    - name: RUN ARISTA COMMAND
      eos_command:
        commands: show ip int br
      when: ansible_network_os == 'eos'
    
    - name: RUN CISCO NXOS COMMAND
      nxos_command:
        commands: show ip int br
      when: ansible_network_os == 'nxos'
    
    - name: RUN JUNOS COMMAND
      junos_command:
        commands: show interface terse
      when: ansible_network_os == 'junos'
