---
- hosts: cisco
  connection: local
  gather_facts: False
  tasks:
    - napalm_get_facts:
        hostname: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        dev_os: "ios"
      register: version

    - debug:
        var=version.ansible_facts.napalm_facts.os_version
