---
- name: Test putting a file onto Cisco IOS/IOS-XE device
  hosts: cisco1
  tasks:
    - name: Copy file
      net_put:
        src: my_file1.txt
        dest : flash:/my_file1.txt
        protocol: scp
