---
- name: Netmiko module
  hosts: cisco1
  gather_facts: False
  tasks:
    - name: Netmiko testing
      netmiko_config:
        host: "{{ ansible_host }}"
        device_type: cisco_ios
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        config_list:
          - logging buffered 20000
          - no logging console

