---
- name: When Testing
  hosts: local
  gather_facts: False
  vars:
    my_str: whatever
    version: "Cisco IOS running version 15.2"

  tasks:
    - command: /bin/false
      register: result
      ignore_errors: True

    - debug:
        msg: "Hello world (failed result)"
      when: result is failed
