---
- name: IOS Example2
  hosts: cisco5
  gather_facts: False
  tasks:
    - name: Global config
      ios_config:
        lines:
          - ip domain name bogus.com
          - ntp server 130.126.24.24
          - ntp server 152.2.21.1
        save_when: changed
        backup: True
