---
- name: VLAN configuration
  hosts: arista
  gather_facts: False
  tasks:
    - name: Merge provided configuration with device configuration
      eos_vlans:
        config:
          - name: Blue300
            vlan_id: 300
            state: active
        state: merged
      when: 'ansible_network_os == "eos"'

- name: IOS Example
  hosts: cisco
  gather_facts: True
  tasks:
    - name: name-server for IOS
      ios_config:
        lines:
          - "ip name-server 8.8.8.8"
