---
- name: Pipe JSON NX-OS
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Executing command
      nxos_command:
        commands: show version | json
      register: output

    - set_fact:
        show_ver: "{{ output['stdout'][0] }}"

    - debug:
        msg: "Platform: {{ show_ver.chassis_id }}"
