---
- name: Exercise 4
  hosts: cisco6
  gather_facts: False
  tasks:
   - name: Clear counters
     ios_command:
       commands:
         - command: clear logging
           prompt: confirm
           answer: ""
     register: clear_log_output
   - name: Print clear log output
     debug:
       var: clear_log_output
