# Requires:
# 'dest_filesystem' to have been previously specified
#
# Returns:
# 'available_space' in bytes
- name: Retrieve available space.
  set_fact:
    available_space_kb: "{{ ansible_facts.net_filesystems_info[dest_filesystem]['spacefree_kb'] }}"

- name: Convert available space to bytes.
  set_fact:
    available_space: "{{ available_space_kb | int * 1024 }}"

- name: Displace bytes available
  debug:
    var: available_space
