---
- name: NXOS Example
  hosts: nxos
  tasks:
    - name: Configure NEXUS VLANs
      vars:
        ansible_connection: httpapi
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        admin_state: "{{ item.admin_state }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"
      notify: write mem

    - name: Configure IP Interface
      vars:
        ansible_connection: httpapi
      nxos_l3_interface:
        name: Ethernet1/4
        ipv4: 10.10.10.1/24
      notify: write mem

    - name: Merge provided configuration with device configuration.
      nxos_l3_interfaces:
        config:
          - name: Ethernet1/3
            ipv4:
              - address: 192.168.1.1/24
                # tag: 5
              - address: 10.1.1.1/24
                secondary: True
                # tag: 10
            ipv6:
              - address: fd5d:12c9:2201:2::1/64
                tag: 6
        state: merged
      tags: new_l3

  handlers:
    - name: write mem
      nxos_command:
        commands: copy run start
      changed_when: True
      tags: wr_mem
