---
- name: NXOS Example
  hosts: nxos
  tasks:
    - name: Configure NEXUS VLANs
      nxos_vlan:
        vlan_id: "{{ item.vlan_id }}"
        admin_state: "{{ item.admin_state }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"
      notify: write mem

    - nxos_l3_interface:
        name: Ethernet1/2
        ipv4: "{{ ip_addr }}/24"
      notify: write mem
      tags: ip_int

  handlers:
    - name: write mem
      nxos_command:
        commands: copy run start
      changed_when: True
      tags: wr_mem
