---

- name: Invalid hostname
  hosts: nxos1
  gather_facts: False

  tasks:
    - name: Executing 'show interface' command
      vars:
        ansible_host: invalid1.lasthop.io
      nxos_command:
        commands: show interface
      register: output

    - debug:
        var: output
