---

- name: Bad auth
  hosts: nxos
  gather_facts: False

  tasks:
    - name: Executing 'show interface' command
      vars:
        ansible_ssh_pass: invalid_pass
      nxos_command:
        commands: show interface
      register: output

    - debug:
        var: output
