---
- name: IOS Example
  hosts: cisco
  tasks:
    - ios_facts:
      tags: facts_only

    - debug:
        var: ansible_net_model

    - ios_command:
        commands: show ip int brief
      register: output

    - debug:
        msg: "{{ output.stdout_lines[0] }}"
