---
- name: IOS Example
  hosts: cisco
  gather_facts: False
  tasks:
    - ios_facts:

    - debug:
        var: ansible_net_model

    - ios_command:
        commands: show ip int brief
      register: output

    - debug:
        msg: "{{ output.stdout_lines[0][5] }}"

    - cli_command:
        command: show ip int brief
      register: output

    - debug:
        var: output
