---
- name: Exercise3
  hosts: nxos
  gather_facts: False
  vars:
    fsm_template: "cisco_nxos_show_ip_bgp_summary.template"

  tasks:
    - name: Executing command
      nxos_command:
        commands: show ip bgp summary
      register: output

    - set_fact:
        show_bgp: "{{ output.stdout[0] | parse_cli_textfsm(fsm_template) }}"

    - debug:
        msg: "{{ show_bgp[0]['STATE_PFXRCD'] }}"
      when: show_bgp != []

    - name: Testing BGP is up
      assert:
        that:
          - show_bgp != []
          - "'Shut' not in show_bgp[0]['STATE_PFXRCD']"
          - "'Idle' not in show_bgp[0]['STATE_PFXRCD']"
          - show_bgp[0]['STATE_PFXRCD'] | int >= 2


#            "STATE_PFXRCD": "Shut (Admin)",
#            "UP_DOWN": "00:01:04",

# ok: [nxos2] => {
#    "msg": "Shut (Admin)"
#}
#ok: [nxos1] => {
#    "msg": "Idle"
#}
