---
- name: "Exercise 1"
  hosts: localhost
  tasks:
    - name: Loops and include (exercise1a)
      include_tasks: subtask1.yml
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4

    - name: Loops, Include, and Dynamic Name (exercise1b)
      include_tasks: "{{ my_tasks }}"
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4

    - name: Tags and include (exercise1c)
      include_tasks: subtask2.yml

    - name: Tags and include (exercise1c-fix1)
      include_tasks: subtask2.yml
      tags:
        - foo1
        - foo2
        - foo3

    - name: Tags and include (exercise1c-fix2)
      include_tasks: subtask2.yml
      tags: always

- name: Exercise 1d (Conditionals)
  hosts: local
  vars:
    var1: foo1
  tasks:
    - name: Conditionals
      include_tasks: subtask3.yml
      when: 'var1 == "foo1"'
