---
- hosts: local
  tasks:
    - name: Loops
      include_tasks: subtask1.yml
      loop:
        - 10.1.1.1
        - 10.1.1.2
        - 10.1.1.3
        - 10.1.1.4

    - name: Loops
      import_tasks: subtask2.yml
