---
- name: Global configuration using includes
  hosts: cisco:arista:nxos
  gather_facts: True
  tasks:
    - name: Include IOS tasks
      include_tasks: "example_tasks/{{ ansible_facts.net_iostype }}/tasks.yml"
      when: ansible_facts.net_iostype is defined and 
            ansible_facts.net_iostype == "IOS"

    - name: Include IOS-XE tasks
      include_tasks: "example_tasks/{{ ansible_facts.net_iostype }}/tasks.yml"
      when: ansible_facts.net_iostype is defined and
            ansible_facts.net_iostype == "IOS-XE"

    - name: Include EOS tasks
      include_tasks: "example_tasks/{{ ansible_network_os }}/tasks.yml"
      when: 'ansible_network_os == "eos"'

    - name: Include NX-OS tasks
      include_tasks: "example_tasks/{{ ansible_network_os }}/tasks.yml"
      when: 'ansible_network_os == "nxos"'

- name: Global configuration using includes
  hosts: juniper
  gather_facts: False
  tasks:
    - name: Include Junos tasks
      include_tasks: "example_tasks/{{ ansible_network_os }}/tasks.yml"
