---
- name: Retrieve Checkpoint File
  hosts: nxos1
  gather_facts: False
  tasks:
    - name: Retrieve checkpoint
      napalm_get_facts:
        filter: checkpoint_file
        optional_args:
          port: 8443

    #- debug:
    #    msg: "{{ napalm_checkpoint_file.splitlines() }}"

    - name: Save the checkpoint
      copy:
        content: "{{ napalm_checkpoint_file }}"
        dest: "{{ inventory_hostname }}.txt"
