- hosts: cisco5
  gather_facts: False
  module_defaults:
    ios_facts:
      gather_subset: min
      gather_network_resources:
      - interfaces
      - l3_interfaces
      - l2_interfaces
      - lldp_global
      - lldp_interfaces
     # - vlans
     # - lacp
     # - lacp_interfaces
     # - lag_interfaces
  tags: play1
  tasks:
    - ios_facts:
