---
- name: Print out variables
  gather_facts: False
  hosts: cisco
  tasks:
    - debug:
        msg: "{{ ansible_host }}"
    - debug:
        msg: "{{ ansible_user }}"
    - debug:
        msg: "{{ ansible_ssh_pass }}"
