---
- name: IOS Example
  hosts: cisco1
  gather_facts: False
  tasks:
    - ios_config:
        parents: ip access-list extended test99
        lines:
            -  permit ip any host 1.1.1.1
        match: strict
      tags: acl_test

    - ios_config:
        before: no ntp
        lines:
            - ntp server 130.126.24.24
            - ntp server 152.2.21.1
        match: strict
      tags: ntp_test
